In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("/content/drive/Shareddrives/21-01 데마팀 화이팅/데이터셋/최종전처리데이터셋.csv", encoding = 'CP949')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1168 entries, 0 to 1167
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0      1168 non-null   int64  
 1   V1              1168 non-null   int64  
 2   name_kor_x      1168 non-null   object 
 3   name_eng        1167 non-null   object 
 4   producer_kor_x  1159 non-null   object 
 5   producer_eng_x  1167 non-null   object 
 6   region_kor      1168 non-null   object 
 7   region_eng      1168 non-null   object 
 8   style_kor       1168 non-null   object 
 9   style_eng       1168 non-null   object 
 10  apv             1165 non-null   float64
 11  ibu             1148 non-null   float64
 12  price           949 non-null    float64
 13  종류              857 non-null    object 
 14  info            1147 non-null   object 
 15  review_eng      930 non-null    object 
 16  mean_average    993 non-null    object 
 17  mean_review     947 non-null    o

In [4]:
Lager = data[data['종류'] == '라거']
Lager.reset_index(inplace=True)

In [5]:
Lager_review = Lager[['review_eng']]
Lager_review['review_eng'][0:10]

0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4    [['500ml can from Karma in Sochi. Pours pale y...
5    [['Appearance is a very lightly hazy pale gold...
6                                                  NaN
7                                                  NaN
8    [['A very nice amber lager, with good malty an...
9    [['This is an easy-to-drink Munich lager witho...
Name: review_eng, dtype: object

In [6]:
import re
Lager_review['review_eng'] = Lager_review['review_eng'].map(lambda x: re.sub('[,\'.[!?]', '', str(x)))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [7]:
Lager_review['review_eng']

0                                                    nan
1                                                    nan
2                                                    nan
3                                                    nan
4      500ml can from Karma in Sochi Pours pale yello...
                             ...                        
134                                                  nan
135                                                  nan
136                                                  nan
137                                                  nan
138                                                  nan
Name: review_eng, Length: 139, dtype: object

In [8]:
import nltk
nltk.download('punkt')
Lager_review['review_eng'] = Lager_review.apply(lambda row:nltk.word_tokenize(row['review_eng']), axis = 1)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [9]:
print(Lager_review.head(30))

                                           review_eng
0                                               [nan]
1                                               [nan]
2                                               [nan]
3                                               [nan]
4   l, can, from, Karma, in, Sochi, Pours, pa...
5   [Appearance, is, a, very, lightly, hazy, pale,...
6                                               [nan]
7                                               [nan]
8   [A, very, nice, amber, lager, with, good, malt...
9   [This, is, an, easy-to-drink, Munich, lager, w...
10                                              [nan]
11  [Light, european, lager, not, bad, -, has, som...
12  [Crystals, clear, pour, minimal, foam, Slightl...
13                                              [nan]
14  [Very, light, malt, and, hops, very, low, bitt...
15  [pours, clear, amber, with, a, small, white, h...
16  [Clear, light, golden, body, with, a, frothy, ...
17  [Light, golden, colour, with,

In [10]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
Lager_review['review_eng'] = Lager_review['review_eng'].apply(lambda x: [WordNetLemmatizer().lemmatize(word, pos='v') for word in x])

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [11]:
tokenized_doc = Lager_review['review_eng'].apply(lambda x: [word for word in x if len(word) > 3])
print(tokenized_doc[:30])

0                                                    []
1                                                    []
2                                                    []
3                                                    []
4     l, from, Karma, Sochi, Pours, pale, yello...
5     [Appearance, very, lightly, hazy, pale, gold, ...
6                                                    []
7                                                    []
8     [very, nice, amber, lager, with, good, malty, ...
9     [This, easy-to-drink, Munich, lager, without, ...
10                                                   []
11    [Light, european, lager, have, some, aroma, fr...
12    [Crystals, clear, pour, minimal, foam, Slightl...
13                                                   []
14    [Very, light, malt, very, bitterness, very, re...
15    [pour, clear, amber, with, small, white, head,...
16    [Clear, light, golden, body, with, frothy, whi...
17    [Light, golden, colour, with, little, head, di.

In [12]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [13]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords 
stop_words = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [55]:
stop_words.extend(['bottle', 'can','good', 'finish', 'Good', 'nice', 'ok','less','easy','pineapple','colour','much','Japanese','German'])

In [56]:
tokens_pos = []
for i in range(len(tokenized_doc)):
  a = nltk.pos_tag(tokenized_doc[i])
  mini = []
  for word, pos in a:
    if 'JJ' in pos and word not in stop_words:
      mini.append(word)
      # tokens_pos.append((word,'JJ'))
  tokens_pos.append(mini)
print(tokens_pos)

[[], [], [], [], ['yellow', 'small', 'white', 'sweet', 'industrial'], ['hazy', 'pale', 'barest', 'white', 'Tiny', 'visible', 'fine', 'disappoint', 'fair', 'touch', 'white', 'sharp', 'lager', 'brilliant', 'fair', 'little', 'bite', 'botanic', 'bitter', 'unpleasant', 'botanic', 'best', 'least', 'fine', 'clean', 'touch', 'in-mouth', 'decent', 'touch', 'unbalance', 'great', 'least', 'drinkable', 'many', 'many', 'better', 'macro-owned', 'traditional', 'European', 'quite', 'bite', 'clear', 'yellow', 'small', 'disappear', 'fast', 'malt', 'bitter', 'small', 'white', 'malt', 'straw', 'citrus', 'moderate', 'grassy', 'unpleasant', 'clear', 'lemon', 'sourness', 'little', 'bite', 'little', 'chemical', 'clean', 'golden', 'golden', 'white', 'touch', 'husky', 'clear', 'little', 'white', 'little', 'bite', 'empty', 'Overall', 'cheap', 'white', 'straw', 'floral', 'light', 'Overall', 'drinkable', 'clear', 'full', 'light', 'standard', 'diminish', 'special', 'white'], [], [], ['small', 'white', 'caramel', 'b

In [57]:
detokenized_doc = []
for i in range(len(Lager_review)):
    t = ' '.join(tokens_pos[i])
    detokenized_doc.append(t)

Lager_review['review_eng'] = detokenized_doc

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words=stop_words, 
max_features= 1000) # 상위 1,000개의 단어를 보존 
X = vectorizer.fit_transform(Lager_review['review_eng'])
X.shape # TF-IDF 행렬의 크기 확인

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['german', 'japanese'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


(139, 732)

In [59]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model=LatentDirichletAllocation(n_components=10,learning_method='online',random_state=777,max_iter=1)

In [60]:
lda_top=lda_model.fit_transform(X)

In [61]:
print(lda_model.components_)
print(lda_model.components_.shape) 

[[0.67037069 0.64764486 0.76374968 ... 0.83468781 0.74148292 0.68165364]
 [0.77167915 0.67593472 0.64600684 ... 0.67770929 0.66618815 0.57247889]
 [0.70084645 0.71080282 0.69760564 ... 0.75234094 0.64660185 0.72259256]
 ...
 [0.71187165 0.7771962  0.73275228 ... 0.71696847 0.67163901 0.74134595]
 [0.82300089 0.72844296 0.64908343 ... 0.72688621 0.8652179  0.77924584]
 [0.61965744 0.76928493 0.78091344 ... 0.93293737 0.59501147 0.71459378]]
(10, 732)


In [62]:
terms = vectorizer.get_feature_names() # 단어 집합. 1,000개의 단어가 저장됨.

def get_topics(components, feature_names, n=5):
    for idx, topic in enumerate(components):
        print("Topic %d:" % (idx+1), [(feature_names[i], topic[i].round(2)) for i in topic.argsort()[:-n - 1:-1]])
get_topics(lda_model.components_,terms)

Topic 1: [('whiskey', 1.03), ('white', 1.0), ('hint', 0.98), ('next', 0.96), ('light', 0.94)]
Topic 2: [('short', 0.97), ('american', 0.94), ('atypical', 0.94), ('pour', 0.92), ('clean', 0.92)]
Topic 3: [('clear', 1.21), ('white', 1.16), ('golden', 1.07), ('usual', 0.95), ('decent', 0.95)]
Topic 4: [('white', 1.26), ('clear', 1.17), ('sweet', 1.13), ('floral', 1.12), ('bitter', 1.04)]
Topic 5: [('white', 1.03), ('ish', 1.0), ('light', 0.99), ('average', 0.95), ('small', 0.95)]
Topic 6: [('golden', 1.07), ('white', 1.03), ('special', 0.99), ('yeasty', 0.97), ('great', 0.95)]
Topic 7: [('white', 1.0), ('right', 0.98), ('lowest', 0.91), ('personal', 0.91), ('cloudy', 0.91)]
Topic 8: [('grassy', 0.95), ('black', 0.92), ('ecru', 0.92), ('dissipate', 0.91), ('dark', 0.91)]
Topic 9: [('skunk', 1.0), ('mediocre', 0.97), ('light', 0.96), ('2020', 0.94), ('popcorn', 0.93)]
Topic 10: [('clear', 0.97), ('yellowish', 0.93), ('license', 0.91), ('extreme', 0.9), ('build', 0.89)]


In [63]:
from gensim import corpora
dictionary = corpora.Dictionary(tokens_pos)
corpus = [dictionary.doc2bow(text) for text in tokens_pos]

In [64]:
import gensim
NUM_TOPICS = 3
ldamodel = gensim.models.ldamodel.LdaModel(corpus, num_topics = NUM_TOPICS, id2word = dictionary, passes =15)
topics = ldamodel.print_topics(num_words = 7)

for topic in topics:
  print(topic)

/usr/local/lib/python3.7/dist-packages/gensim/models/ldamodel.py:1077: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  score += np.sum(cnt * logsumexp(Elogthetad + Elogbeta[:, int(id)]) for id, cnt in doc)
/usr/local/lib/python3.7/dist-packages/gensim/models/ldamodel.py:1077: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  score += np.sum(cnt * logsumexp(Elogthetad + Elogbeta[:, int(id)]) for id, cnt in doc)
/usr/local/lib/python3.7/dist-packages/gensim/models/ldamodel.py:1077: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  score += np.sum(cnt * logsumexp(Elogthetad + Elogbeta[:, int(id)]) for

(0, '0.048*"light" + 0.039*"white" + 0.037*"sweet" + 0.025*"clear" + 0.021*"small" + 0.016*"thin" + 0.014*"golden"')
(1, '0.070*"white" + 0.045*"golden" + 0.037*"clear" + 0.025*"bitter" + 0.022*"sweet" + 0.021*"light" + 0.020*"little"')
(2, '0.005*"south" + 0.005*"thank" + 0.005*"Sweetish" + 0.005*"asia" + 0.005*"sulfur" + 0.005*"icky" + 0.005*"inexpensive"')


In [51]:
! pip install pyLDAvis

ERROR: Operation cancelled by user
^C


In [65]:
import pyLDAvis
import pyLDAvis.gensim_models as gensimvis
pyLDAvis.enable_notebook()

In [66]:
vis = gensimvis.prepare(ldamodel, corpus, dictionary)

In [67]:
pyLDAvis.display(vis)