In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("/content/drive/Shareddrives/21-01 데마팀 화이팅/데이터셋/최종전처리데이터셋.csv", encoding = 'CP949')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1168 entries, 0 to 1167
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0      1168 non-null   int64  
 1   V1              1168 non-null   int64  
 2   name_kor_x      1168 non-null   object 
 3   name_eng        1167 non-null   object 
 4   producer_kor_x  1159 non-null   object 
 5   producer_eng_x  1167 non-null   object 
 6   region_kor      1168 non-null   object 
 7   region_eng      1168 non-null   object 
 8   style_kor       1168 non-null   object 
 9   style_eng       1168 non-null   object 
 10  apv             1165 non-null   float64
 11  ibu             1148 non-null   float64
 12  price           949 non-null    float64
 13  종류              857 non-null    object 
 14  info            1147 non-null   object 
 15  review_eng      930 non-null    object 
 16  mean_average    993 non-null    object 
 17  mean_review     947 non-null    o

In [4]:
Porter = data[data['종류'] == '포터']
Porter.reset_index(inplace=True)

In [5]:
Porter_review = Porter[['review_eng']]
Porter_review['review_eng'][0:10]

0                                                  NaN
1    [['Pours a very dark brown with a off white he...
2    [['Aroma of chocolate, dried plums, coffee, ca...
3    [['Pours a dark brown beer, aroma is liquorice...
4    [['Poured a dark brown color with an averaged ...
5    [['Nice stout, but a little too 'watery'/too b...
6    [['Pours black with a white foamy head. Aromas...
7    [['We're in front of a dark beer with a creamy...
8    [['Pours ruby red with a good head. Fruity and...
9    [['Blackish ruby, dark chocolate malt aroma, m...
Name: review_eng, dtype: object

In [6]:
import re
Porter_review['review_eng'] = Porter_review['review_eng'].map(lambda x: re.sub('[,\'.[!?]', '', str(x)))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [7]:
Porter_review['review_eng']

0                                                   nan
1     Pours a very dark brown with a off white head ...
2     Aroma of chocolate dried plums coffee caramel ...
3     Pours a dark brown beer aroma is liquorice dar...
4     Poured a dark brown color with an averaged siz...
5     Nice stout but a little too watery/too bitter ...
6     Pours black with a white foamy head Aromas & t...
7     Were in front of a dark beer with a creamy hea...
8     Pours ruby red with a good head Fruity and com...
9     Blackish ruby dark chocolate malt aroma medium...
10                                                  nan
11    Pours a dark brown colour with a beige coloure...
12                                                  nan
13    22oz bottle Poured a dark brown color with a s...
14    Black colour with dense beige head Malty roast...
15    Pours black with an olive sheen and a thin tan...
16    650ml bottle Opaque darkest brown colour with ...
17    Can from the brewery in Ashland Oregon  Bl

In [8]:
import nltk
nltk.download('punkt')
Porter_review['review_eng'] = Porter_review.apply(lambda row:nltk.word_tokenize(row['review_eng']), axis = 1)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [9]:
print(Porter_review.head(30))

                                           review_eng
0                                               [nan]
1   [Pours, a, very, dark, brown, with, a, off, wh...
2   [Aroma, of, chocolate, dried, plums, coffee, c...
3   [Pours, a, dark, brown, beer, aroma, is, liquo...
4   [Poured, a, dark, brown, color, with, an, aver...
5   [Nice, stout, but, a, little, too, watery/too,...
6   [Pours, black, with, a, white, foamy, head, Ar...
7   [Were, in, front, of, a, dark, beer, with, a, ...
8   [Pours, ruby, red, with, a, good, head, Fruity...
9   [Blackish, ruby, dark, chocolate, malt, aroma,...
10                                              [nan]
11  [Pours, a, dark, brown, colour, with, a, beige...
12                                              [nan]
13  [22oz, bottle, Poured, a, dark, brown, color, ...
14  [Black, colour, with, dense, beige, head, Malt...
15  [Pours, black, with, an, olive, sheen, and, a,...
16  l, bottle, Opaque, darkest, brown, colour...
17  [Can, from, the, brewery, in,

In [10]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
Porter_review['review_eng'] = Porter_review['review_eng'].apply(lambda x: [WordNetLemmatizer().lemmatize(word, pos='v') for word in x])

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [11]:
tokenized_doc = Porter_review['review_eng'].apply(lambda x: [word for word in x if len(word) > 3])
print(tokenized_doc[:30])

0                                                    []
1     [Pours, very, dark, brown, with, white, head, ...
2     [Aroma, chocolate, plums, coffee, caramel, cru...
3     [Pours, dark, brown, beer, aroma, liquorice, d...
4     [Poured, dark, brown, color, with, average, si...
5     [Nice, stout, little, watery/too, bitter, tast...
6     [Pours, black, with, white, foamy, head, Aroma...
7     [Were, front, dark, beer, with, creamy, head, ...
8     [Pours, ruby, with, good, head, Fruity, comple...
9     [Blackish, ruby, dark, chocolate, malt, aroma,...
10                                                   []
11    [Pours, dark, brown, colour, with, beige, colo...
12                                                   []
13    [22oz, bottle, Poured, dark, brown, color, wit...
14    [Black, colour, with, dense, beige, head, Malt...
15    [Pours, black, with, olive, sheen, thin, head,...
16    l, bottle, Opaque, darkest, brown, colour...
17    [from, brewery, Ashland, Oregon, Black, with, .

In [12]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [13]:
tokens_pos = []
for i in range(len(tokenized_doc)):
  a = nltk.pos_tag(tokenized_doc[i])
  mini = []
  for word, pos in a:
    if 'JJ' in pos:
      mini.append(word)
      # tokens_pos.append((word,'JJ'))
  tokens_pos.append(mini)
print(tokens_pos)

[[], ['dark', 'white', 'bitter', 'finish', 'unstable', 'foamy', 'dark', 'black', 'sweetish', 'herbal', 'toasty', 'creamy', 'soft', 'authentic', 'watered-down', 'rich', 'robust', 'great', 'linger', 'many', 'special', 'Clear', 'dark', 'brown', 'black', 'minimal', 'brown', 'light', 'soft', 'Steady', 'Thypical', 'clear', 'drinkable', 'update', 'useful', 'beige', 'dark', 'subtle', 'sweetish', 'dark', 'beige', 'dark', 'subtle', 'sweetish', 'dark', 'clear', 'dark', 'stable', 'beige', 'sweet', 'light', 'bitter', 'finish', 'texture', 'solid', 'easy', 'good', 'hard', 'thirst', 'flavour', 'thick', 'hard-working', 'chocolate', 'biscuity-malt', 'earthy', 'finish', 'beige', 'bitter', 'finish', 'bitterness', 'finish', 'thin', 'thin', 'smoky', 'fake', 'hint', 'thin', 'many', 'fail', 'full', 'expensive', 'bar-', 'friend', 'little', 'ferment', 'soft', 'note', 'soft', 'solid'], ['roasty', 'More', 'porter', 'dark', 'dark', 'black', 'note', 'brown', 'persistent', 'black', 'layer', 'strip', 'dark', 'black',

In [14]:
detokenized_doc = []
for i in range(len(Porter_review)):
    t = ' '.join(tokens_pos[i])
    detokenized_doc.append(t)

Porter_review['review_eng'] = detokenized_doc

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [15]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [16]:
from nltk.corpus import stopwords 
stop_words = stopwords.words('english')
stop_words.extend(['bottle', 'can'])

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
stop_words.extend(['bottle', 'can'])
vectorizer = TfidfVectorizer(stop_words=stop_words, 
max_features= 1000) # 상위 1,000개의 단어를 보존 
X = vectorizer.fit_transform(Porter_review['review_eng'])
X.shape # TF-IDF 행렬의 크기 확인

(29, 352)

In [18]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model=LatentDirichletAllocation(n_components=10,learning_method='online',random_state=777,max_iter=1)

In [19]:
lda_top=lda_model.fit_transform(X)

In [20]:
print(lda_model.components_)
print(lda_model.components_.shape) 

[[0.79187794 0.76431083 0.90515014 ... 0.72478228 0.75955739 0.81377397]
 [1.04117467 0.9764342  0.89682609 ... 0.61131177 0.86330178 1.01156438]
 [0.88762959 0.94182745 0.81785678 ... 0.88403478 0.96094234 0.74382994]
 ...
 [0.9161285  0.89958364 0.71164903 ... 0.84895957 0.74953127 0.74970389]
 [0.84101504 0.76517276 0.89849568 ... 0.88982895 1.03681821 0.75769337]
 [0.86944363 0.80302338 0.8594141  ... 0.76751092 0.90187708 0.83416442]]
(10, 352)


In [21]:
terms = vectorizer.get_feature_names() # 단어 집합. 1,000개의 단어가 저장됨.

def get_topics(components, feature_names, n=5):
    for idx, topic in enumerate(components):
        print("Topic %d:" % (idx+1), [(feature_names[i], topic[i].round(2)) for i in topic.argsort()[:-n - 1:-1]])
get_topics(lda_model.components_,terms)

Topic 1: [('total', 1.13), ('average', 1.05), ('plenty', 1.03), ('mouth', 1.02), ('present', 1.0)]
Topic 2: [('dosed', 1.14), ('black', 1.09), ('thypical', 1.07), ('lemon', 1.06), ('neutral', 1.06)]
Topic 3: [('ashiness', 1.25), ('early', 1.11), ('light', 1.1), ('complete', 1.09), ('soft', 1.07)]
Topic 4: [('liquorice', 1.1), ('remarkable', 1.1), ('robust', 1.06), ('sweetness', 1.02), ('bitterness', 1.01)]
Topic 5: [('earthy', 1.1), ('bar', 1.1), ('tasty', 1.08), ('olive', 1.08), ('creamy', 1.06)]
Topic 6: [('smooth', 1.1), ('brown', 1.05), ('blackish', 1.05), ('noble', 1.05), ('virtual', 1.04)]
Topic 7: [('small', 1.13), ('understand', 1.06), ('caramel', 1.06), ('happy', 1.06), ('colour', 1.06)]
Topic 8: [('dark', 1.11), ('finish', 1.08), ('thin', 1.08), ('walnuts', 1.07), ('black', 1.04)]
Topic 9: [('written', 1.04), ('special', 1.03), ('typical', 1.03), ('neutral', 1.02), ('ashiness', 1.02)]
Topic 10: [('finish', 1.14), ('fine', 1.08), ('black', 1.08), ('undertone', 1.05), ('strong'

In [22]:
from gensim import corpora
dictionary = corpora.Dictionary(tokens_pos)
corpus = [dictionary.doc2bow(text) for text in tokens_pos]

In [23]:
import gensim
NUM_TOPICS = 5
ldamodel = gensim.models.ldamodel.LdaModel(corpus, num_topics = NUM_TOPICS, id2word = dictionary, passes =15)
topics = ldamodel.print_topics(num_words = 7)

for topic in topics:
  print(topic)

(0, '0.048*"dark" + 0.048*"black" + 0.041*"light" + 0.029*"nice" + 0.025*"finish" + 0.023*"sweet" + 0.022*"thin"')
(1, '0.053*"black" + 0.037*"finish" + 0.036*"dark" + 0.019*"bitter" + 0.017*"good" + 0.017*"nice" + 0.016*"last"')
(2, '0.058*"black" + 0.039*"little" + 0.035*"bitter" + 0.034*"brown" + 0.025*"bite" + 0.025*"dark" + 0.020*"beige"')
(3, '0.003*"dark" + 0.003*"black" + 0.003*"light" + 0.003*"finish" + 0.003*"sweet" + 0.003*"nice" + 0.003*"soft"')
(4, '0.051*"dark" + 0.035*"brown" + 0.027*"bitter" + 0.026*"black" + 0.025*"thin" + 0.019*"last" + 0.018*"finish"')


In [24]:
! pip install pyLDAvis

     |████████████████████████████████| 1.7MB 4.9MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 9.9MB 43.1MB/s 
     |████████████████████████████████| 15.3MB 307kB/s 
  Created wheel for pyLDAvis: filename=pyLDAvis-3.3.1-cp37-none-any.whl size=136870 sha256=574394653fd9ca9c5c3c37d930f3c1c6e5c27a63b0269d0923797aa2c78802ab
  Stored in directory: /root/.cache/pip/wheels/a0/9c/fc/c6e00689d35c82cf96a8adc70edfe7ba7904374fdac3240ac2
Successfully built pyLDAvis
ERROR: tensorflow 2.4.1 has requirement numpy~=1.19.2, but you'll have numpy 1.20.2 which is incompatible.
ERROR: google-colab 1.0.0 has requirement pandas~=1.1.0; python_version >= "3.0", but you'll have pandas 1.2.4 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0

In [ ]:
import pyLDAvis
import pyLDAvis.gensim_models as gensimvis
pyLDAvis.enable_notebook()

/usr/local/lib/python3.7/dist-packages/past/types/oldstr.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Iterable


In [ ]:
vis = gensimvis.prepare(ldamodel, corpus, dictionary)

In [ ]:
pyLDAvis.display(vis)